on: push
name: Subir imagen a docker hub
jobs:
  build-and-push:
    name: build and push image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
          username: faceporte
          password: pesaschile123        
    - name: build and push to docker
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: faceporte/action:${{ github.sha }}
